kind: pipeline
type: kubernetes
name: build

steps:

- name: Base
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    repo: getais/devops-toolbox
    tags:
      - latest
      - 2.1

- name: NodeJS 14
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    repo: getais/devops-toolbox
    dockerfile: Dockerfile.Node14
    tags:
      - 2.1-node14