kind: pipeline
type: docker
name: build

steps:

- name: Docker image
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_TOKEN
    repo: getais/devops-toolbox
    tags:
      - latest
      - 1.0
