FROM centos:8
MAINTAINER Tomas Liumparas <tomas.liumparas@gmail.com>
LABEL maintainer="tomas.liumparas@gmail.com"

ENV HOME=/opt/app/root

# Install OS packages
RUN yum install -y \
    wget \
    unzip \
    tree \
    jq \

    # envsubst
    gettext

RUN yum module install -y nodejs:14
RUN npm install yarn

